{% set name = "dartsim" %}
{% set version = "6.16.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/dartsim/dart/archive/v{{ version }}.tar.gz
    sha256: d7af169aca40f63e8fae0541421bdbf48a36bcc5e236414d0d3ae2bf4eada489
    patches:
      # Disable tutorials and examples to save build time
      - patches/disable-tutorials-examples.patch  # [win]
      # Avoid -A x64 for Ninja/NMake when building dartpy on Windows
      - patches/fix-setup-msvc-ninja.patch  # [win]
      # Allow relocating dartpy build temp dir to avoid Windows disk exhaustion
      - patches/dartpy-build-temp-env.patch  # [win]

build:
  number: 2

outputs:
  - name: dartsim-cpp
    script: build_cpp.sh  # [unix]
    script: bld_cpp.bat  # [win]
    build:
      skip: true  # [(linux and py<312) or (win and (py<312 or py>314))]
      run_exports:
        - {{ pin_subpackage('dartsim-cpp', max_pin='x.x') }}
      ignore_run_exports:
        - console_bridge
        - spdlog
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - doxygen
        - make                   # [not win]
        - ninja                  # [win]
        - perl                   # [win]
        - pkg-config
      host:
        - assimp
        - bullet-cpp
        - console_bridge
        - eigen
        - fcl
        - fmt
        - freeglut  # [not osx]
        - imgui
        - ipopt
        - libboost-devel
        - libgl-devel  # [linux]
        - libglu       # [linux]
        - libode
        - nlopt
        - octomap
        - openscenegraph
        - pagmo
        - pagmo-devel
        - tinyxml2
        - urdfdom
        - spdlog
      run:
        - eigen
        - octomap
    test:
      commands:
        - test -f $PREFIX/lib/libdart.dylib  # [osx]
        - test -f $PREFIX/lib/libdart.so  # [linux]
        - test -f $PREFIX/share/dart/cmake/dart_collision-odeTargets.cmake  # [not win]
        - test -f $PREFIX/share/dart/cmake/dart_collision-bulletTargets.cmake  # [not win]
        - if not exist %LIBRARY_LIB%\\dart.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\dart\\cmake\\dart_collision-odeTargets.cmake exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\dart\\cmake\\dart_collision-bulletTargets.cmake exit 1  # [win]
      downstreams:
        - gz-physics8

  - name: dartpy
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    build:
      skip: true  # [(linux and py<312) or (win and (py<312 or py>314))]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - doxygen
        - make                   # [not win]
        - ninja                  # [win]
        - perl                   # [win]
        - pkg-config
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
      host:
        # C++ deps
        - assimp
        - bullet-cpp
        - console_bridge
        - eigen
        - fcl
        - fmt
        - freeglut  # [not osx]
        - imgui
        - ipopt
        - libboost-devel
        - libgl-devel  # [linux]
        - libglu       # [linux]
        - libode
        - nlopt
        - octomap
        - openscenegraph
        - pagmo
        - pagmo-devel
        - tinyxml2
        - urdfdom
        - spdlog
        - xorg-libxfixes  # [linux]
        # Python deps
        - numpy
        - pip
        - python
        - requests
        - setuptools
      run:
        - libgl   # [linux]
        - libglu  # [linux]
        - numpy
        - python
    test:
      imports:
        - dartpy

  - name: dartsim
    build:
      skip: true  # [(linux and py<312) or (win and (py<312 or py>314))]
      run_exports:
        - {{ pin_subpackage('dartsim-cpp', max_pin='x.x') }}
    requirements:
      run:
        - {{ pin_subpackage('dartsim-cpp', exact=True) }}
        - {{ pin_subpackage('dartpy', exact=True) }}  # [not ((aarch64 or ppc64le) and py<312)]
        - python
        - numpy
    test:
      imports:
        - dartpy  # [not ((aarch64 or ppc64le) and py<312)]
      commands:
        - test -f $PREFIX/lib/libdart.dylib  # [osx]
        - test -f $PREFIX/lib/libdart.so  # [linux]
        - test -f $PREFIX/share/dart/cmake/dart_collision-odeTargets.cmake  # [not win]
        - test -f $PREFIX/share/dart/cmake/dart_collision-bulletTargets.cmake  # [not win]
        - if not exist %LIBRARY_LIB%\\dart.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\dart\\cmake\\dart_collision-odeTargets.cmake exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\dart\\cmake\\dart_collision-bulletTargets.cmake exit 1  # [win]

about:
  home: http://dartsim.github.io/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: The DART (Dynamic Animation and Robotics Toolkit) library provides data structures and algorithms for kinematic and dynamic applications in robotics and computer animation.
  description: The DART (Dynamic Animation and Robotics Toolkit) library provides data structures and algorithms for kinematic and dynamic applications in robotics and computer animation.
  dev_url: https://github.com/dartsim/dart

extra:
  recipe-maintainers:
    - jeongseok-meta
    - jslee02
    - traversaro
    - wolfv
