{% set name = "dartsim" %}
{% set version = "6.9.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/dartsim/dart/archive/v{{ version }}.tar.gz
    sha256: 624c00b65e3a753cba50de038620860c86e2ac47b1793ae51f9427a4bcb14c32
    patches:
      - 1478.patch  # [win]
      - 1541.patch  # [win]

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - pkg-config
    - make                   # [not win]
    - ninja                  # [win]
    - perl                   # [win]
  host:
    - assimp
    - boost-cpp
    - bullet
    - console_bridge
    - eigen
    - fcl
    - flann
    - libccd
    - libode
    - lz4-c
    - octomap
    - tinyxml2
    - urdfdom
    - freeglut  # [win]

  run:
    - assimp
    - boost-cpp
    - bullet
    - console_bridge
    - eigen
    - fcl
    - flann
    - libccd
    - libode
    - lz4-c
    - octomap
    - tinyxml2
    - urdfdom
    - freeglut  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libdart.dylib  # [osx]
    - test -f $PREFIX/lib/libdart.so  # [linux]
    - if not exist %LIBRARY_LIB%\\dart.lib exit 1  # [win]

about:
  home: http://dartsim.github.io/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: The DART (Dynamic Animation and Robotics Toolkit) library provides data structures and algorithms for kinematic and dynamic applications in robotics and computer animation.
  description: The DART (Dynamic Animation and Robotics Toolkit) library provides data structures and algorithms for kinematic and dynamic applications in robotics and computer animation.
  dev_url: https://github.com/dartsim/dart

extra:
  recipe-maintainers:
    - traversaro
    - wolfv
