{% set name = "dartsim" %}
{% set version = "6.14.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/dartsim/dart/archive/v{{ version }}.tar.gz
    sha256: f5fc7f5cb1269cc127a1ff69be26247b9f3617ce04ff1c80c0f3f6abc7d9ab70

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - console_bridge
    - fmt           # [osx]
    - freeglut      # [aarch64 or ppc64le]
    - imgui         # [aarch64]
    - libboost      # [osx]
    - libstdcxx-ng  # [aarch64 or ppc64le]
    - spdlog

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux64]
    - {{ cdt('mesa-libglu-devel') }}  # [linux64]
    - {{ stdlib("c") }}
    - cmake
    - doxygen
    - make                   # [not win]
    - ninja                  # [win]
    - perl                   # [win]
    - pkg-config

  host:
    - assimp
    - bullet-cpp
    - console_bridge
    - eigen
    - fcl
    - fmt
    - freeglut  # [not osx]
    - imgui  # [not ppc64le]
    - ipopt
    - libboost-devel  # [not ppc64le]
    - libode
    - nlopt
    - octomap
    - openscenegraph  # [linux64 or osx or win]
    - pagmo  # [not ppc64le]
    - pagmo-devel  # [not ppc64le]
    - tinyxml2
    - urdfdom
    - spdlog

  run:
    - eigen
    - glfw
    - libccd-double
    - octomap
    - sdl2
    - xorg-libxi

test:
  commands:
    - test -f $PREFIX/lib/libdart.dylib  # [osx]
    - test -f $PREFIX/lib/libdart.so  # [linux]
    - test -f $PREFIX/share/dart/cmake/dart_collision-odeTargets.cmake  # [not win]
    - test -f $PREFIX/share/dart/cmake/dart_collision-bulletTargets.cmake  # [not win]
    - if not exist %LIBRARY_LIB%\\dart.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\dart\\cmake\\dart_collision-odeTargets.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\dart\\cmake\\dart_collision-bulletTargets.cmake exit 1  # [win]

about:
  home: http://dartsim.github.io/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: The DART (Dynamic Animation and Robotics Toolkit) library provides data structures and algorithms for kinematic and dynamic applications in robotics and computer animation.
  description: The DART (Dynamic Animation and Robotics Toolkit) library provides data structures and algorithms for kinematic and dynamic applications in robotics and computer animation.
  dev_url: https://github.com/dartsim/dart

extra:
  recipe-maintainers:
    - jslee02
    - traversaro
    - wolfv
